export const fields = [
  {
    id: "Computing & Informatics",
    e: "💻",
    n: 12,
    icon: "computer",
    color: "bg-blue-100 text-blue-600",
    desc: "Software, data, AI and IT innovators.",
  },
  {
    id: "Engineering",
    e: "⚙️",
    n: 10,
    icon: "settings",
    color: "bg-orange-100 text-orange-600",
    desc: "Design, build and solve real-world challenges.",
  },
  {
    id: "Natural & Applied Sciences",
    e: "🔬",
    n: 8,
    icon: "science",
    color: "bg-emerald-100 text-emerald-600",
    desc: "Explore the world through science and discovery.",
  },
  {
    id: "Business & Management",
    e: "📈",
    n: 9,
    icon: "trending_up",
    color: "bg-purple-100 text-purple-600",
    desc: "Lead, innovate and create impact.",
  },
];

export const mentors = [
  {
    name: "Tlotlo Mphato",
    initials: "TM",
    f: "Computing & Informatics",
    r: "AI Engineer @ FNB Botswana",
    d: "Computing",
    sk: ["AI/ML", "Python", "NLP", "LLMs"],
    a: "Available now",
    av: 1,
    st: 28,
    ca: 42,
    bio: "Specializes in ML systems, LLMs and real-world AI applications.",
    about: "I help students build practical AI skills through real-world projects and career guidance.",
    rating: "5.0",
    reviews: 28,
    yearsExp: "4+",
    successRate: "95%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAAON97J21Z6YunUVZGStqRGM4DqRPYYtiI-78EtrcHC6VkLMRN0xVK_X9TNoMmVMnRQL8hVeBk6_4rbYen0wxTS_8YsuFVtXfxk7xtKeJAu6euCGXkL2bt9RSqs-CRLjsalhUvo3oKHiE9zNKcawKSbwZDQ8YpSv5odOlpJdsZaSlPJ9B4vxjUnrN3LwjEHZryOuxR1nug38SBxrkQx0BCvGZRaXe1evsKJEWX9EMHiPq_ZTtlc0NrNl_UFYqgQuQDo8VRRjxSFLZc",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuDK1N_c0iTd8S9WmzIr93E0X9MBenZEydyJBJZbLEobgBJrLUcaCVUCdpsbrUl6GoFmF-gFeOU7u7Yg8hRNF9h3jyxFs247tn5sFdG7fZ8igsgEejBBJvY881N3C5dh1KYbRtUEUzQUZtQW6aIHCY3Hr67x9dD1fROGTTdp_hqw59JzQZ3P8ySUQZHxjPOpy_5odpisMG7FL6PfcEiFzZ-Csn6-ClcpXOpBeTH3O5Kn9LvSRXbP1h45HtFo2tJlqMJyfQTh4Osps7RV",
  },
  {
    name: "Lesgo Kgosi",
    initials: "LK",
    f: "Computing & Informatics",
    r: "Data Scientist @ Letshego",
    d: "Computing",
    sk: ["Data Science", "SQL", "Python"],
    a: "Available Fri",
    av: 0,
    st: 19,
    ca: 30,
    bio: "Helping students break into data with real projects.",
    about: "I mentor aspiring data scientists through practical, hands-on data projects.",
    rating: "4.8",
    reviews: 19,
    yearsExp: "3+",
    successRate: "90%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnArfPDsAj0sJtl4y1QmESo84UyO8OVH0-7JcUdOumMWKbCmmXO_Q_SCxic-RmqqwiO-ah8zh6ilC7b5cbFhQDZpLZwGMzLRcl4u9dtviqNvUMNep8AxfG8E3gNDmJlXLITc_b3NvW8GFK4XCBKwiEMInc_hLscqQHcxjWLiWiD-PDm7w98nENmapZ3DTQaPzF5rY5L9syozdu2WrNQMgd_o22r5KAZLVxbNSi5ZDp_I4n43bxPqvcfYrDS8R5gIY7rt1RP5GfjZ1x",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnArfPDsAj0sJtl4y1QmESo84UyO8OVH0-7JcUdOumMWKbCmmXO_Q_SCxic-RmqqwiO-ah8zh6ilC7b5cbFhQDZpLZwGMzLRcl4u9dtviqNvUMNep8AxfG8E3gNDmJlXLITc_b3NvW8GFK4XCBKwiEMInc_hLscqQHcxjWLiWiD-PDm7w98nENmapZ3DTQaPzF5rY5L9syozdu2WrNQMgd_o22r5KAZLVxbNSi5ZDp_I4n43bxPqvcfYrDS8R5gIY7rt1RP5GfjZ1x",
  },
  {
    name: "Boitumelo Pheko",
    initials: "BP",
    f: "Computing & Informatics",
    r: "Software Engineer @ Orange",
    d: "Computing",
    sk: ["Web Dev", "React", "Node.js"],
    a: "Weekend only",
    av: 0,
    st: 34,
    ca: 40,
    bio: "Full-stack development & system design enthusiast.",
    about: "I guide students from fundamentals to building production-ready applications.",
    rating: "4.9",
    reviews: 34,
    yearsExp: "5+",
    successRate: "92%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWGBpaKRZxY_f3JCkNt8giz_dOY1_8z0mhK6fbkfuoQET2xbBlGzbAMjYcrntxRQMXeq1Z1RMoZfinCo8FjuumGBKmSXlJEDrgvpW6HuSFHArVaediSYgHjvtLcCMhYE7YgX9vtl2GTnTjMgkYXtBJ_HMlcM6gSwPu1Y8hFsGh_OwBCXQxa9XSg4r3XIzui7xw5q32mRsetqpqNrh97VliH7Qk7bKvIcfQzoWuJSwiEQ27JyeBCAOtGcpfeNlIFBN_3Xh9lvH_3CrG",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWGBpaKRZxY_f3JCkNt8giz_dOY1_8z0mhK6fbkfuoQET2xbBlGzbAMjYcrntxRQMXeq1Z1RMoZfinCo8FjuumGBKmSXlJEDrgvpW6HuSFHArVaediSYgHjvtLcCMhYE7YgX9vtl2GTnTjMgkYXtBJ_HMlcM6gSwPu1Y8hFsGh_OwBCXQxa9XSg4r3XIzui7xw5q32mRsetqpqNrh97VliH7Qk7bKvIcfQzoWuJSwiEQ27JyeBCAOtGcpfeNlIFBN_3Xh9lvH_3CrG",
  },
  {
    name: "Kabelo Setlhare",
    initials: "KS",
    f: "Computing & Informatics",
    r: "Cybersecurity Analyst",
    d: "Computing",
    sk: ["Security", "Network", "Linux"],
    a: "Available now",
    av: 1,
    st: 16,
    ca: 25,
    bio: "Passionate about securing systems and ethical hacking.",
    about: "I help students break into cybersecurity with hands-on labs and cert guidance.",
    rating: "4.7",
    reviews: 16,
    yearsExp: "3+",
    successRate: "88%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDyzM5kknX-ooagWpM73AKRAYXhqqbtDlK_dPtOOYyQ7sUfzSYcvpQjQCPNkN8it1WdM3GTluqo6WlnNr8BulN6CNKnHlpMo3GCNBG8G6ORre-fNFmxiksusF4WKT2_aj6IjC7EJv_pqxgi4ZAKPyA191mI4zD9WA3c0WN5KuM5KNkJwuwixvnhH8qxMiSVMtkuVKMZqZpeGkIgEEUK6MmeBXSRPGKex1IojtND7K8iSJqhAWQkI4u2j8J5a9VZd_wrG63zyeWkhbI-",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuDyzM5kknX-ooagWpM73AKRAYXhqqbtDlK_dPtOOYyQ7sUfzSYcvpQjQCPNkN8it1WdM3GTluqo6WlnNr8BulN6CNKnHlpMo3GCNBG8G6ORre-fNFmxiksusF4WKT2_aj6IjC7EJv_pqxgi4ZAKPyA191mI4zD9WA3c0WN5KuM5KNkJwuwixvnhH8qxMiSVMtkuVKMZqZpeGkIgEEUK6MmeBXSRPGKex1IojtND7K8iSJqhAWQkI4u2j8J5a9VZd_wrG63zyeWkhbI-",
  },
  // Engineering mentors
  {
    name: "Prof. Sarah Jenkins",
    initials: "SJ",
    f: "Engineering",
    r: "Mech. Design Prof.",
    d: "Mechanical Eng.",
    sk: ["Mechanical", "Manufacturing"],
    a: "Available now",
    av: 1,
    st: 7,
    ca: 8,
    bio: "Design reviews, feasibility, engineering careers.",
    about: "Guiding the next generation of mechanical engineers.",
    rating: "4.9",
    reviews: 22,
    yearsExp: "12+",
    successRate: "97%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuArapzQRIOmPoijO5w3epQFWdRQ2uBnPAUkx7KgYfeUWZ6sJClI8uuTlJfsMh7BDOQRALrp6l0EMK8moFiMZDMSauzgF2BQ8f7Pbpm6m8UrKRP7KFOS1npCQwgrMgp5vAiZxT7lM8nTw1v5RjOVzFB2mH7xEy_m-VZzbqGu74CJ9QYNAjoWKzlBi1w3iWd4T9xmwuekcacRKSlpAJtWQTvbaPwbELXrZAEdwFn1PoVGnUwfRCoTC6spt0MF8f0sbDwJEzn8lHdDBj4T",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuArapzQRIOmPoijO5w3epQFWdRQ2uBnPAUkx7KgYfeUWZ6sJClI8uuTlJfsMh7BDOQRALrp6l0EMK8moFiMZDMSauzgF2BQ8f7Pbpm6m8UrKRP7KFOS1npCQwgrMgp5vAiZxT7lM8nTw1v5RjOVzFB2mH7xEy_m-VZzbqGu74CJ9QYNAjoWKzlBi1w3iWd4T9xmwuekcacRKSlpAJtWQTvbaPwbELXrZAEdwFn1PoVGnUwfRCoTC6spt0MF8f0sbDwJEzn8lHdDBj4T",
  },
  {
    name: "Engr. Craig Moyo",
    initials: "CM",
    f: "Engineering",
    r: "Civil Engineer",
    d: "Civil & Env.",
    sk: ["Structural", "Infrastructure"],
    a: "Available Thu",
    av: 0,
    st: 3,
    ca: 6,
    bio: "Structural design, sustainable infrastructure.",
    about: "Passionate about building resilient communities through engineering.",
    rating: "4.6",
    reviews: 14,
    yearsExp: "8+",
    successRate: "85%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDbbnySErAPvxjwqnQnZhBFbLbZtMK4-69GX_wuIiE41YJ3yZmo6lJdeIbjhcVovLXiFDHHTjeuEUh_tWbaswbAKdp4q8qP-aJZIB_JEPENaUPt7N5cYo6-arZ-6Um3jWGPRqdwvzEp_JJkhYz-6bEfKU7vj0HZOyF-e1EmWyBA6lZurWQq8Sey785f6eWCmGantnj75p-swXSR4YZ6bOCU0ZgVJSJxjc_RX3FM2zyzlOR5GgL6aqnUCfVBdKvj_687UtZHvRrxQ3fI",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuDbbnySErAPvxjwqnQnZhBFbLbZtMK4-69GX_wuIiE41YJ3yZmo6lJdeIbjhcVovLXiFDHHTjeuEUh_tWbaswbAKdp4q8qP-aJZIB_JEPENaUPt7N5cYo6-arZ-6Um3jWGPRqdwvzEp_JJkhYz-6bEfKU7vj0HZOyF-e1EmWyBA6lZurWQq8Sey785f6eWCmGantnj75p-swXSR4YZ6bOCU0ZgVJSJxjc_RX3FM2zyzlOR5GgL6aqnUCfVBdKvj_687UtZHvRrxQ3fI",
  },
  {
    name: "Dr. Lerato Nkosi",
    initials: "LN",
    f: "Engineering",
    r: "Electrical Engineer",
    d: "Electrical & Elec.",
    sk: ["Power Systems", "Renewable"],
    a: "Available now",
    av: 1,
    st: 5,
    ca: 7,
    bio: "Power systems, renewable energy.",
    about: "Empowering students to innovate in sustainable energy.",
    rating: "4.8",
    reviews: 18,
    yearsExp: "10+",
    successRate: "93%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCX8rsjFElVuNKhcvQHVs7_6efYqjhtHHAOQ8AmvEwM9ehgOpQ-FNZgwcOA0QoniVhM7bN8CYSRneV0jh9V-m8D4_gThplA1LUbyAb1wxrVCRSWXGiE_3qQAfa90QbNl0sbv3KuKp4DAQvT3KDYQiZ5MbeiAcpLa7h6UnwuEIutVpseSw8Pn-68edNFMRwqOtYdG9hCEkLvaGtpXh-U84BR3VNI3Tbrp5CaDLN36m8ioo8u5Z7uUO8coihgijl2DYIIv8BppGDR6Hyp",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuCX8rsjFElVuNKhcvQHVs7_6efYqjhtHHAOQ8AmvEwM9ehgOpQ-FNZgwcOA0QoniVhM7bN8CYSRneV0jh9V-m8D4_gThplA1LUbyAb1wxrVCRSWXGiE_3qQAfa90QbNl0sbv3KuKp4DAQvT3KDYQiZ5MbeiAcpLa7h6UnwuEIutVpseSw8Pn-68edNFMRwqOtYdG9hCEkLvaGtpXh-U84BR3VNI3Tbrp5CaDLN36m8ioo8u5Z7uUO8coihgijl2DYIIv8BppGDR6Hyp",
  },
  {
    name: "Engr. Boitumelo Seth",
    initials: "BS",
    f: "Engineering",
    r: "Mechatronics Lead",
    d: "Mechanical Eng.",
    sk: ["Robotics", "Control", "AI"],
    a: "Available now",
    av: 1,
    st: 6,
    ca: 8,
    bio: "Robotics, AI control systems.",
    about: "Bridging mechanical engineering with cutting-edge AI.",
    rating: "4.9",
    reviews: 25,
    yearsExp: "7+",
    successRate: "94%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCXgLT34ZcAN9_VzU9We-mI-zvJBZaeYgDe7EOCm0UMUAfvdBWqHAskuzOLwdUzW4E-XxTyU4fKIh70TvWC66ziXRrsEyUDoYl3_rT1fFaZt6bHAUPBSE9m6BXAd_IaQHznzU0uZYRdd8hohHJph0eZFOgBrlC5KxF4Qvwt9aG1U0YjDr4-WDob4ElKmGlvX18w6cuvY_ogukvn222-B3fwIp1ibs4jAjPF6vQzDQbfy-qZbZLkQYRovJuu9UEwqa8UTF8PL3-Rf4bj",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuCXgLT34ZcAN9_VzU9We-mI-zvJBZaeYgDe7EOCm0UMUAfvdBWqHAskuzOLwdUzW4E-XxTyU4fKIh70TvWC66ziXRrsEyUDoYl3_rT1fFaZt6bHAUPBSE9m6BXAd_IaQHznzU0uZYRdd8hohHJph0eZFOgBrlC5KxF4Qvwt9aG1U0YjDr4-WDob4ElKmGlvX18w6cuvY_ogukvn222-B3fwIp1ibs4jAjPF6vQzDQbfy-qZbZLkQYRovJuu9UEwqa8UTF8PL3-Rf4bj",
  },
  // Natural & Applied Sciences mentors
  {
    name: "Dr. Kevin Botha",
    initials: "KB",
    f: "Natural & Applied Sciences",
    r: "Environmental Scientist",
    d: "Natural Sciences",
    sk: ["Research", "Data", "Ecology"],
    a: "Available Wed",
    av: 0,
    st: 6,
    ca: 6,
    bio: "Field research, scientific writing.",
    about: "Passionate about environmental conservation and scientific mentorship.",
    rating: "4.5",
    reviews: 12,
    yearsExp: "9+",
    successRate: "83%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuArapzQRIOmPoijO5w3epQFWdRQ2uBnPAUkx7KgYfeUWZ6sJClI8uuTlJfsMh7BDOQRALrp6l0EMK8moFiMZDMSauzgF2BQ8f7Pbpm6m8UrKRP7KFOS1npCQwgrMgp5vAiZxT7lM8nTw1v5RjOVzFB2mH7xEy_m-VZzbqGu74CJ9QYNAjoWKzlBi1w3iWd4T9xmwuekcacRKSlpAJtWQTvbaPwbELXrZAEdwFn1PoVGnUwfRCoTC6spt0MF8f0sbDwJEzn8lHdDBj4T",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuArapzQRIOmPoijO5w3epQFWdRQ2uBnPAUkx7KgYfeUWZ6sJClI8uuTlJfsMh7BDOQRALrp6l0EMK8moFiMZDMSauzgF2BQ8f7Pbpm6m8UrKRP7KFOS1npCQwgrMgp5vAiZxT7lM8nTw1v5RjOVzFB2mH7xEy_m-VZzbqGu74CJ9QYNAjoWKzlBi1w3iWd4T9xmwuekcacRKSlpAJtWQTvbaPwbELXrZAEdwFn1PoVGnUwfRCoTC6spt0MF8f0sbDwJEzn8lHdDBj4T",
  },
  {
    name: "Dr. Palesa Molefe",
    initials: "PM",
    f: "Natural & Applied Sciences",
    r: "Biochemist",
    d: "Natural Sciences",
    sk: ["Research", "Lab", "Bio"],
    a: "Available now",
    av: 1,
    st: 3,
    ca: 7,
    bio: "Protein research, lab techniques.",
    about: "Helping students navigate biochemistry research careers.",
    rating: "4.7",
    reviews: 15,
    yearsExp: "6+",
    successRate: "87%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCX8rsjFElVuNKhcvQHVs7_6efYqjhtHHAOQ8AmvEwM9ehgOpQ-FNZgwcOA0QoniVhM7bN8CYSRneV0jh9V-m8D4_gThplA1LUbyAb1wxrVCRSWXGiE_3qQAfa90QbNl0sbv3KuKp4DAQvT3KDYQiZ5MbeiAcpLa7h6UnwuEIutVpseSw8Pn-68edNFMRwqOtYdG9hCEkLvaGtpXh-U84BR3VNI3Tbrp5CaDLN36m8ioo8u5Z7uUO8coihgijl2DYIIv8BppGDR6Hyp",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuCX8rsjFElVuNKhcvQHVs7_6efYqjhtHHAOQ8AmvEwM9ehgOpQ-FNZgwcOA0QoniVhM7bN8CYSRneV0jh9V-m8D4_gThplA1LUbyAb1wxrVCRSWXGiE_3qQAfa90QbNl0sbv3KuKp4DAQvT3KDYQiZ5MbeiAcpLa7h6UnwuEIutVpseSw8Pn-68edNFMRwqOtYdG9hCEkLvaGtpXh-U84BR3VNI3Tbrp5CaDLN36m8ioo8u5Z7uUO8coihgijl2DYIIv8BppGDR6Hyp",
  },
  // Add one more for each field to have more options
  {
    name: "Armaan Khan",
    initials: "AK",
    f: "Computing & Informatics",
    r: "Senior Software Engineer @ Google",
    d: "Computing",
    sk: ["System Design", "AI/ML"],
    a: "Available now",
    av: 1,
    st: 35,
    ca: 50,
    bio: "Expert in distributed systems and AI/ML architecture.",
    about: "I help students break into top tech companies through structured mentorship.",
    rating: "5.0",
    reviews: 42,
    yearsExp: "8+",
    successRate: "96%",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCXgLT34ZcAN9_VzU9We-mI-zvJBZaeYgDe7EOCm0UMUAfvdBWqHAskuzOLwdUzW4E-XxTyU4fKIh70TvWC66ziXRrsEyUDoYl3_rT1fFaZt6bHAUPBSE9m6BXAd_IaQHznzU0uZYRdd8hohHJph0eZFOgBrlC5KxF4Qvwt9aG1U0YjDr4-WDob4ElKmGlvX18w6cuvY_ogukvn222-B3fwIp1ibs4jAjPF6vQzDQbfy-qZbZLkQYRovJuu9UEwqa8UTF8PL3-Rf4bj",
    imgLarge: "https://lh3.googleusercontent.com/aida-public/AB6AXuDK1N_c0iTd8S9WmzIr93E0X9MBenZEydyJBJZbLEobgBJrLUcaCVUCdpsbrUl6GoFmF-gFeOU7u7Yg8hRNF9h3jyxFs247tn5sFdG7fZ8igsgEejBBJvY881N3C5dh1KYbRtUEUzQUZtQW6aIHCY3Hr67x9dD1fROGTTdp_hqw59JzQZ3P8ySUQZHxjPOpy_5odpisMG7FL6PfcEiFzZ-Csn6-ClcpXOpBeTH3O5Kn9LvSRXbP1h45HtFo2tJlqMJyfQTh4Osps7RV",
  },
];